"""Catalogo de ejercicios de oratoria con niveles de dificultad.

Cada ejercicio tiene: titulo, consigna, estructura a seguir, consejos
(vocabulario, muletillas a evitar) y duracion sugerida.
"""

EXERCISES: list[dict] = [
    # ============ ESPAÑOL ============
    # ----- Principiante -----
    {
        "id": "es-1-presentacion",
        "language": "es",
        "level": "principiante",
        "category": "presentación",
        "title": "Preséntate en un minuto",
        "prompt": "Contá quién sos, qué hacés y qué te gusta hacer.",
        "structure": ["Tu nombre y de dónde sos", "A qué te dedicás", "Un hobby o algo que te guste"],
        "tips": ["Usá conectores: 'además', 'por otro lado'", "Evitá empezar con 'bueno...'", "Mirá el micrófono como si fuera una persona"],
        "minutes": 1,
    },
    {
        "id": "es-2-rutina",
        "language": "es",
        "level": "principiante",
        "category": "rutina",
        "title": "Tu día de hoy",
        "prompt": "Contá qué hiciste desde que te levantaste hasta ahora.",
        "structure": ["A qué hora te levantaste", "Las tareas del día", "Algo interesante que pasó"],
        "tips": ["Usá verbos en pasado: 'me levanté', 'fui', 'hice'", "Ordenate con las horas del día", "Sumá una emoción: 'me llamó la atención que...'"],
        "minutes": 2,
    },
    {
        "id": "es-3-lugar",
        "language": "es",
        "level": "principiante",
        "category": "descripción",
        "title": "Describe tu barrio o ciudad",
        "prompt": "Describí el lugar donde vivís.",
        "structure": ["Dónde queda y cómo se llama", "Cómo es (tranquilo, movido...)", "Qué es lo que más te gusta"],
        "tips": ["Usá adjetivos descriptivos: 'tranquilo', 'amplio', 'pintoresco'", "Compará: 'más que', 'menos que'"],
        "minutes": 1,
    },
    {
        "id": "es-4-futuro",
        "language": "es",
        "level": "principiante",
        "category": "futuro",
        "title": "Tus planes para el fin de semana",
        "prompt": "Contá qué pensás hacer este fin de semana.",
        "structure": ["Un plan concreto", "Con quién o dónde", "Qué te gustaría que pase"],
        "tips": ["Usá futuro: 'voy a', 'pienso', 'me gustaría'", "Sumá detalles para que suene natural"],
        "minutes": 1,
    },
    # ----- Intermedio -----
    {
        "id": "es-5-historia",
        "language": "es",
        "level": "intermedio",
        "category": "historia",
        "title": "Contá una anécdota",
        "prompt": "Contá una anécdota breve que te haya pasado esta semana.",
        "structure": ["El contexto: dónde y cuándo", "Qué pasó", "Cómo terminó y qué aprendiste"],
        "tips": ["Cuidá las muletillas: si pensás, hacé una pausa corta", "Usá 'de repente', 'al final'", "No cuentes todo de corrido: respirá entre ideas"],
        "minutes": 2,
    },
    {
        "id": "es-6-opinion",
        "language": "es",
        "level": "intermedio",
        "category": "opinión",
        "title": "Da tu opinión sobre un tema",
        "prompt": "Elegí un tema de actualidad o debate y da tu opinión.",
        "structure": ["Tu postura en una frase", "Un argumento", "Un ejemplo concreto"],
        "tips": ["Palabras para opinar: 'en mi opinión', 'considero que', 'desde mi punto de vista'", "Evitá 'no sé', 'nada que ver'", "Cerrá con una idea fuerte"],
        "minutes": 2,
    },
    {
        "id": "es-7-profesional",
        "language": "es",
        "level": "intermedio",
        "category": "profesional",
        "title": "Describe tu trabajo",
        "prompt": "Explicá en qué trabajás y qué hacés.",
        "structure": ["Tu rol en una frase", "Una tarea típica de tu día", "Qué es lo que más te gusta"],
        "tips": ["Usá vocabulario del rubro", "Evitá 'y nada más', 'y eso'", "Pensá en un cliente que no conoce tu trabajo"],
        "minutes": 1,
    },
    {
        "id": "es-8-persona",
        "language": "es",
        "level": "intermedio",
        "category": "descripción",
        "title": "Describe a alguien que admires",
        "prompt": "Describí a una persona que admire o que te haya inspirado.",
        "structure": ["Quién es y cómo la conociste", "Sus cualidades", "Qué aprendiste de esa persona"],
        "tips": ["Usá 'es una persona que...', 'se destaca por...'", "Sumá una historia breve como ejemplo", "Evitá repetir 'muy' todo el tiempo"],
        "minutes": 2,
    },
    # ----- Avanzado -----
    {
        "id": "es-9-discurso",
        "language": "es",
        "level": "avanzado",
        "category": "discurso",
        "title": "Prepará un discurso de 2 minutos",
        "prompt": "Elegí un tema que conozcas y armá un mini discurso con apertura, desarrollo y cierre.",
        "structure": ["Apertura que capte atención", "Tres ideas principales", "Cierre con llamado o conclusión"],
        "tips": ["Anotá solo palabras clave, no leas", "Controlá el ritmo: pausa tras cada idea", "Variá el volumen para enfatizar"],
        "minutes": 2,
    },
    {
        "id": "es-10-debate",
        "language": "es",
        "level": "avanzado",
        "category": "argumentación",
        "title": "Defendé una postura contraria",
        "prompt": "Elegí un tema y defendé la postura contraria a la tuya.",
        "structure": ["Reconocé la postura opuesta", "Dos argumentos a favor", "Cierre que responda una objeción"],
        "tips": ["Usá 'si bien', 'no obstante', 'sin embargo'", "Escuchá tus propias muletillas mientras hablás", "No repitas la misma idea con otras palabras"],
        "minutes": 2,
    },
    {
        "id": "es-11-metas",
        "language": "es",
        "level": "avanzado",
        "category": "futuro",
        "title": "Tus metas a 5 años",
        "prompt": "Contá tu visión a 5 años y cómo planeás llegar.",
        "structure": ["La meta principal", "El plan paso a paso", "Los posibles obstáculos y cómo superarlos"],
        "tips": ["Verbos de intención: 'pretendo', 'me propongo', 'aspiro a'", "Mostrá seguridad: evitá 'capaz', 'más o menos'"],
        "minutes": 2,
    },
    {
        "id": "es-12-improvisacion",
        "language": "es",
        "level": "avanzado",
        "category": "improvisación",
        "title": "Habla sin preparación",
        "prompt": "Elegí un tema al azar (un animal, un lugar, un objeto) y hablá 90 segundos sin prepararte.",
        "structure": ["Definí el tema en una frase", "Tres cosas que sabés de él", "Una conexión con tu vida"],
        "tips": ["Organizate sobre la marcha: 'en primer lugar', 'además', 'finalmente'", "Si trabás, repetí la última idea con otras palabras", "Aceptá el error y seguí"],
        "minutes": 2,
    },
    # ============ INGLÉS ============
    {
        "id": "en-1-intro",
        "language": "en",
        "level": "principiante",
        "category": "introduction",
        "title": "Introduce yourself in a minute",
        "prompt": "Tell who you are, what you do and what you like.",
        "structure": ["Your name and where you're from", "What you do", "A hobby or interest"],
        "tips": ["Use connectors: 'also', 'on the other hand'", "Avoid starting with 'well...'", "Speak as if talking to a real person"],
        "minutes": 1,
    },
    {
        "id": "en-2-routine",
        "language": "en",
        "level": "principiante",
        "category": "routine",
        "title": "Your day today",
        "prompt": "Tell what you did from when you woke up until now.",
        "structure": ["What time you woke up", "The tasks of the day", "Something interesting that happened"],
        "tips": ["Use past tense: 'I woke up', 'I went', 'I did'", "Keep it ordered by time", "Add a feeling: 'it caught my attention that...'"],
        "minutes": 2,
    },
    {
        "id": "en-3-place",
        "language": "en",
        "level": "principiante",
        "category": "description",
        "title": "Describe your neighborhood or city",
        "prompt": "Describe the place where you live.",
        "structure": ["Where it is and its name", "How it is (quiet, busy...)", "What you like most about it"],
        "tips": ["Use descriptive adjectives: 'peaceful', 'spacious', 'charming'", "Compare: 'more than', 'less than'"],
        "minutes": 1,
    },
    {
        "id": "en-4-future",
        "language": "en",
        "level": "principiante",
        "category": "future",
        "title": "Your plans for the weekend",
        "prompt": "Tell what you plan to do this weekend.",
        "structure": ["A concrete plan", "With whom or where", "What you would like to happen"],
        "tips": ["Use future: 'I'm going to', 'I plan to', 'I would like to'", "Add details to sound natural"],
        "minutes": 1,
    },
    {
        "id": "en-5-story",
        "language": "en",
        "level": "intermedio",
        "category": "story",
        "title": "Tell a story",
        "prompt": "Tell a short story that happened to you this week.",
        "structure": ["The context: where and when", "What happened", "How it ended and what you learned"],
        "tips": ["Watch your filler words: if you think, pause briefly", "Use 'suddenly', 'in the end'", "Breathe between ideas"],
        "minutes": 2,
    },
    {
        "id": "en-6-opinion",
        "language": "en",
        "level": "intermedio",
        "category": "opinion",
        "title": "Give your opinion on a topic",
        "prompt": "Pick a topic of current debate and give your opinion.",
        "structure": ["Your stance in one sentence", "One argument", "A concrete example"],
        "tips": ["Use: 'in my opinion', 'I believe that', 'from my point of view'", "Avoid 'I don't know', 'whatever'", "Close with a strong idea"],
        "minutes": 2,
    },
    {
        "id": "en-7-work",
        "language": "en",
        "level": "intermedio",
        "category": "professional",
        "title": "Describe your job",
        "prompt": "Explain what you do for a living.",
        "structure": ["Your role in one sentence", "A typical task of your day", "What you like the most"],
        "tips": ["Use industry vocabulary", "Avoid 'and stuff', 'that's it'", "Imagine a client who doesn't know your job"],
        "minutes": 1,
    },
    {
        "id": "en-8-person",
        "language": "en",
        "level": "intermedio",
        "category": "description",
        "title": "Describe someone you admire",
        "prompt": "Describe a person you admire or who inspired you.",
        "structure": ["Who they are and how you met", "Their qualities", "What you learned from them"],
        "tips": ["Use 'they are someone who...', 'they stand out for...'", "Add a short example story", "Avoid repeating 'very' all the time"],
        "minutes": 2,
    },
    {
        "id": "en-9-speech",
        "language": "en",
        "level": "avanzado",
        "category": "speech",
        "title": "Prepare a 2-minute speech",
        "prompt": "Pick a topic you know well and give a mini speech with opening, body and closing.",
        "structure": ["An opening that grabs attention", "Three main ideas", "A closing with a call to action"],
        "tips": ["Write only keywords, don't read", "Control pace: pause after each idea", "Vary your volume to emphasize"],
        "minutes": 2,
    },
    {
        "id": "en-10-debate",
        "language": "en",
        "level": "avanzado",
        "category": "argumentation",
        "title": "Defend an opposite view",
        "prompt": "Pick a topic and defend the view opposite to yours.",
        "structure": ["Acknowledge the other side", "Two arguments for it", "A closing that answers one objection"],
        "tips": ["Use 'although', 'however', 'nevertheless'", "Notice your own filler words while speaking", "Don't repeat the same idea with different words"],
        "minutes": 2,
    },
    {
        "id": "en-11-goals",
        "language": "en",
        "level": "avanzado",
        "category": "future",
        "title": "Your goals in 5 years",
        "prompt": "Tell your 5-year vision and how you plan to get there.",
        "structure": ["The main goal", "The step-by-step plan", "Possible obstacles and how to overcome them"],
        "tips": ["Use intention verbs: 'I intend to', 'I aim to'", "Sound confident: avoid 'maybe', 'sort of'"],
        "minutes": 2,
    },
    {
        "id": "en-12-improv",
        "language": "en",
        "level": "avanzado",
        "category": "improvisation",
        "title": "Speak off the cuff",
        "prompt": "Pick a random topic (an animal, a place, an object) and speak for 90 seconds without preparing.",
        "structure": ["Define the topic in one sentence", "Three things you know about it", "A connection to your life"],
        "tips": ["Organize as you go: 'first of all', 'besides', 'finally'", "If you get stuck, restate the last idea", "Accept mistakes and keep going"],
        "minutes": 2,
    },
    {
        "id": "es-13-conquista",
        "language": "es",
        "level": "principiante",
        "category": "social",
        "title": "Iniciar una conversación",
        "prompt": "Simulá que querés iniciar una charla con una persona que te interesa.",
        "structure": ["Un saludo natural y una pregunta abierta", "Un tema del momento (el lugar, la ocasión)", "Escuchá su respuesta y seguí con otra pregunta"],
        "tips": ["Preguntas abiertas: '¿qué te pareció...?', '¿cómo llegaste acá?'", "No invadas el espacio personal", "Mirá a los ojos y sonreí"],
        "minutes": 1,
    },
    {
        "id": "es-14-conquista2",
        "language": "es",
        "level": "intermedio",
        "category": "social",
        "title": "Coquetear con naturalidad",
        "prompt": "Practicá una conversación con humor y un cumplido sincero.",
        "structure": ["Un cumplido específico (no sobre el físico primero)", "Humor ligero sin burlarte", "Una invitación o propuesta concreta"],
        "tips": ["Cumplido específico: 'se nota que sabés de...'", "Evitá piropos y 'chistes' a costa de otros", "Déjale espacio para responder"],
        "minutes": 2,
    },
    {
        "id": "es-15-jefe",
        "language": "es",
        "level": "principiante",
        "category": "laboral",
        "title": "Hablar con tu jefe",
        "prompt": "Practicá cómo plantearle algo a tu jefe (un pedido, un reporte o una idea).",
        "structure": ["Saludo y contexto breve", "Tu pedido o reporte en una o dos frases", "Qué necesitás de él/ella para continuar"],
        "tips": ["Andá al punto sin rodeos", "Usá 'quería proponerte...', 'necesitaría tu visto bueno...'", "Evitá quejarte sin aportar soluciones"],
        "minutes": 1,
    },
    {
        "id": "es-16-jefe2",
        "language": "es",
        "level": "avanzado",
        "category": "laboral",
        "title": "Dar una mala noticia a tu jefe",
        "prompt": "Practicá comunicar un problema o error sin dramatizar.",
        "structure": ["El hecho claro, sin culpas", "El impacto en una frase", "Tu plan para resolverlo o mitigarlo"],
        "tips": ["Primero el hecho, después el impacto", "Nunca ocultes ni eches la culpa", "Llegá con al menos una solución"],
        "minutes": 1,
    },
    {
        "id": "es-17-entrevista",
        "language": "es",
        "level": "intermedio",
        "category": "laboral",
        "title": "Entrevista de trabajo: presentate",
        "prompt": "Simulá el clásico 'contame sobre vos' de una entrevista.",
        "structure": ["Quién sos y tu experiencia en una línea", "Tus logros más relevantes", "Por qué querés este puesto"],
        "tips": ["Conectá tu experiencia con el puesto", "Usá números o resultados concretos", "Cerrá mostrando interés por la empresa"],
        "minutes": 2,
    },
    {
        "id": "es-18-entrevista2",
        "language": "es",
        "level": "avanzado",
        "category": "laboral",
        "title": "Entrevista: tu mayor desafío",
        "prompt": "Contá una situación difícil que superaste (método STAR).",
        "structure": ["Situación: el contexto en dos frases", "Tarea y acción: qué hiciste", "Resultado: qué conseguiste"],
        "tips": ["Método STAR: Situación, Tarea, Acción, Resultado", "Mostrá tu rol, no el del equipo", "Cerrá con lo que aprendiste"],
        "minutes": 2,
    },
    {
        "id": "es-19-cliente",
        "language": "es",
        "level": "intermedio",
        "category": "ventas",
        "title": "Convencer a un cliente",
        "prompt": "Practicá cómo presentar un producto o servicio para que un cliente quiera comprar.",
        "structure": ["Preguntá primero qué necesita", "Proponé tu solución como respuesta a esa necesidad", "Cerrá invitando al siguiente paso"],
        "tips": ["Primero el beneficio, después el precio", "Evitá 'no sé', 'capaz'", "Confirmá: '¿te sirve que lo dejemos listo?'"],
        "minutes": 2,
    },
    {
        "id": "es-20-objecion",
        "language": "es",
        "level": "avanzado",
        "category": "ventas",
        "title": "Manejar una objeción",
        "prompt": "El cliente dice 'es muy caro'. Practicá tu respuesta.",
        "structure": ["Validá la objeción", "Replanteá el valor de lo que ofrecés", "Proponé una opción o plan"],
        "tips": ["Nunca digas 'es barato'", "Convertí el costo en inversión", "Preguntá: '¿qué te haría decidir?'"],
        "minutes": 1,
    },
    {
        "id": "es-21-pareja",
        "language": "es",
        "level": "avanzado",
        "category": "social",
        "title": "Hablar con tu pareja irritada",
        "prompt": "Tu pareja está molesta por algo. Practicá cómo acercarte.",
        "structure": ["Validá la emoción: 'entiendo que te molestó...'", "Escuchá sin interrumpir ni justificarte", "Proponé resolverlo juntos"],
        "tips": ["No minimices ni digas 'tranquilizate'", "No lleves la conversación a tu defensa", "Si hace falta, pedí pausa: 'quiero escucharte bien'"],
        "minutes": 2,
    },
    {
        "id": "es-22-hijos",
        "language": "es",
        "level": "intermedio",
        "category": "familia",
        "title": "Hablar con tus hijos",
        "prompt": "Practicá explicar algo importante a un niño o adolescente.",
        "structure": ["Decile lo importante con palabras simples", "Escuchá qué entendió o cómo se siente", "Cerrá con un acuerdo o consecuencia clara"],
        "tips": ["Agachate a su altura y bajá el tono", "Preguntá: '¿qué entendiste?'", "No hagas preguntas retóricas"],
        "minutes": 1,
    },
    {
        "id": "es-23-vecino",
        "language": "es",
        "level": "avanzado",
        "category": "conflicto",
        "title": "Resolver un conflicto con un vecino",
        "prompt": "Un vecino está ofuscado por un ruido. Practicá cómo resolverlo sin pelear.",
        "structure": ["Saludá con calma y reconocé su molestia", "Escuchá su versión completa", "Proponé una solución concreta y pedile acuerdo"],
        "tips": ["No te pongas a la defensiva", "Usá 'yo siento que...', evitá 'vos siempre...'", "Busquen un punto en común"],
        "minutes": 2,
    },
    {
        "id": "en-13-flirt1",
        "language": "en",
        "level": "principiante",
        "category": "social",
        "title": "Start a conversation",
        "prompt": "Pretend you want to start a chat with someone you like.",
        "structure": ["A natural greeting and an open question", "A topic of the moment (the place, the occasion)", "Listen to their answer and ask a follow-up"],
        "tips": ["Open questions: 'what did you think of...?', 'how did you get here?'", "Respect personal space", "Make eye contact and smile"],
        "minutes": 1,
    },
    {
        "id": "en-14-flirt2",
        "language": "en",
        "level": "intermedio",
        "category": "social",
        "title": "Flirt naturally",
        "prompt": "Practice a conversation with humor and a sincere compliment.",
        "structure": ["A specific compliment (not about looks first)", "Light humor without teasing", "A concrete invitation or proposal"],
        "tips": ["Specific compliment: 'you really know about...'", "Avoid cheesy lines", "Give them room to respond"],
        "minutes": 2,
    },
    {
        "id": "en-15-boss",
        "language": "en",
        "level": "principiante",
        "category": "work",
        "title": "Talk to your boss",
        "prompt": "Practice raising a request, report or idea to your boss.",
        "structure": ["Greeting and brief context", "Your request or report in one or two sentences", "What you need from them to move forward"],
        "tips": ["Get to the point", "Use: 'I wanted to propose...', 'I'd need your sign-off...'", "Don't complain without offering solutions"],
        "minutes": 1,
    },
    {
        "id": "en-16-boss2",
        "language": "en",
        "level": "avanzado",
        "category": "work",
        "title": "Break bad news to your boss",
        "prompt": "Practice communicating a problem or mistake without drama.",
        "structure": ["The clear fact, no blame", "The impact in one sentence", "Your plan to fix or mitigate it"],
        "tips": ["Fact first, impact second", "Never hide it or shift blame", "Arrive with at least one solution"],
        "minutes": 1,
    },
    {
        "id": "en-17-interview",
        "language": "en",
        "level": "intermedio",
        "category": "work",
        "title": "Job interview: introduce yourself",
        "prompt": "Practice the classic 'tell me about yourself'.",
        "structure": ["Who you are and your experience in one line", "Your most relevant achievements", "Why you want this role"],
        "tips": ["Connect your experience to the role", "Use numbers or concrete results", "Close showing interest in the company"],
        "minutes": 2,
    },
    {
        "id": "en-18-interview2",
        "language": "en",
        "level": "avanzado",
        "category": "work",
        "title": "Interview: your biggest challenge",
        "prompt": "Tell about a difficult situation you overcame (STAR method).",
        "structure": ["Situation: context in two sentences", "Task and action: what you did", "Result: what you achieved"],
        "tips": ["STAR: Situation, Task, Action, Result", "Show your role, not just the team's", "Close with what you learned"],
        "minutes": 2,
    },
    {
        "id": "en-19-client",
        "language": "en",
        "level": "intermedio",
        "category": "sales",
        "title": "Convince a client",
        "prompt": "Practice presenting a product or service so a client wants to buy.",
        "structure": ["Ask what they need first", "Present your solution as the answer to that need", "Close by inviting the next step"],
        "tips": ["Benefit first, price second", "Avoid 'I don't know', 'maybe'", "Confirm: 'shall I get it ready for you?'"],
        "minutes": 2,
    },
    {
        "id": "en-20-objection",
        "language": "en",
        "level": "avanzado",
        "category": "sales",
        "title": "Handle an objection",
        "prompt": "The client says 'it's too expensive'. Practice your answer.",
        "structure": ["Acknowledge the objection", "Reframe the value you offer", "Propose an option or plan"],
        "tips": ["Never say 'it's cheap'", "Turn the cost into an investment", "Ask: 'what would help you decide?'"],
        "minutes": 1,
    },
    {
        "id": "en-21-partner",
        "language": "en",
        "level": "avanzado",
        "category": "social",
        "title": "Talk to your partner when upset",
        "prompt": "Your partner is upset about something. Practice how to approach.",
        "structure": ["Validate the emotion: 'I understand that upset you...'", "Listen without interrupting or defending", "Propose solving it together"],
        "tips": ["Don't minimize or say 'calm down'", "Don't turn it into your defense", "If needed, ask for a pause"],
        "minutes": 2,
    },
    {
        "id": "en-22-kids",
        "language": "en",
        "level": "intermedio",
        "category": "family",
        "title": "Talk to your kids",
        "prompt": "Practice explaining something important to a child or teenager.",
        "structure": ["Say the important thing in simple words", "Listen to what they understood or feel", "Close with a clear agreement or consequence"],
        "tips": ["Get to their eye level and lower your voice", "Ask: 'what did you understand?'", "Avoid rhetorical questions"],
        "minutes": 1,
    },
    {
        "id": "en-23-neighbor",
        "language": "en",
        "level": "avanzado",
        "category": "conflict",
        "title": "Resolve a conflict with a neighbor",
        "prompt": "A neighbor is upset about noise. Practice solving it without fighting.",
        "structure": ["Greet calmly and acknowledge their frustration", "Hear their full version", "Propose a concrete solution and ask for agreement"],
        "tips": ["Don't get defensive", "Use 'I feel that...', avoid 'you always...'", "Find common ground"],
        "minutes": 2,
    },
]


def list_exercises(language: str, level: str | None = None) -> list[dict]:
    lang = "es" if language.lower().startswith("es") else "en"
    items = [e for e in EXERCISES if e["language"] == lang]
    if level in ("principiante", "intermedio", "avanzado"):
        items = [e for e in items if e["level"] == level]
    return items


def daily_exercise(language: str) -> dict:
    """Ejercicio del dia: rota de forma determinista segun la fecha."""
    from datetime import date

    items = list_exercises(language)
    today = date.today()
    idx = (today.year * 10000 + today.month * 100 + today.day) % len(items)
    return items[idx]
